### ISSUE TITLE
Precompiled ipa file 

### ISSUE THREAD

**Issue by CrCrate** [Pullerz/DankPod#1]
Would love to have a precompiled ipa in the code/releases, I don’t have a Mac but really want to try this.

**Comment by Pullerz** [comment]
Hey man apologies for the tardy reply - I've been very busy for the last couple days. I've just committed an [IPA](https://github.com/Pullerz/DankPod/blob/master/DankPod.ipa) file - I am unsure whether it will work due to the fact that I think you have to have registered all device Ids in the developer system which can use the app and obviously your device Id won't be registered with my developer account - nevertheless it's worth a try. The same IPA file is available if you go to [here](https://royalblue.org.uk/apps/DankPod) on your iDevice you can download it directly there without the need for a computer. Let me know how it goes and I'll do my best to help :)

**Comment by CrCrate** [comment]
Thanks, the presigned one works, and I’m on jb anyway so I’ll be able to use the ipa.
